---
benchmark:
  threads: 1
  clients: 1
  data_volume: 1024
  ratio: "1:1"
  port: 6378
  expiry_range: "1800000000-3600000000"

controller:
  thread_life_limit: 2
  control_frequency: 10
  execute_frequency: 1
  stop_tolerance: 5
  early_finish_tolerance: 5
  log_path: "./controller_log"

time_steps: 900
profile_path: "./profile.txt"
log_path: "./logs"
error_path: "./errors"
connection_retry: 1
servers:
  - 192.168.200.165
