---
benchmark:
  threads: 2
  clients: 200
  data_volume: 1024
  ratio: "1:1"
  port: 6378
  expiry_range: "1800-3600"

time_steps: 10
thread_life_limit: 10
profile_path: "./profile.txt"
log_path: "./logs"
error_path: "./errors"
connection_retry: 1
servers:
  - 192.168.200.165
